require('babel-polyfill')
require('./vendor.less')
require("github-markdown-css") 
require('./dist/highlight.min.js')
marked = require('marked')
jQuery = require('jquery/dist/jquery.min.js')
require('bootstrap/dist/js/bootstrap.min.js')
Vue = require('vue/dist/vue.runtime.min.js')
VueResource = require('vue-resource/dist/vue-resource.min.js')
VueRouter = require('vue-router/dist/vue-router.min.js')
