require('babel-polyfill')
require('./vendor.less')
require("github-markdown-css")
require("highlight/lib/vendor/highlight.js/styles/github.css") 
marked = require('marked')
hljs2 = require('highlight/lib/vendor/highlight.js/highlight.js')
console.log(hljs2)
jQuery = require('jquery/dist/jquery.min.js')
require('bootstrap/dist/js/bootstrap.min.js')
Vue = require('vue/dist/vue.runtime.min.js')
VueResource = require('vue-resource/dist/vue-resource.min.js')
VueRouter = require('vue-router/dist/vue-router.min.js')
